### ISSUE TITLE
Simplify site header

### ISSUE THREAD

**Issue by ggrossetie** [feelpp/antora-ui#1]
- [ ] Remove `Docs` menu since the content is empty
- [ ] Remove `Home` entry since it's already possible to go back to the home page by clicking the 'Home' icon or the "Feel++ Docs" text at the top left corner)
- [ ] Rename "Feel++" menu to "Manuals"
- [ ] Move GitHub Repository and GitHub Issue Tracker" to the new "Community" menu
- [ ] Move the "Slack" icon/link to the new "Community" menu
- [ ] Move "Feel++" logo to the top left corner
- [ ] Introduce a new "Community" menu
   - Chat -> Slack
   - Source -> GitHub
   - Issues -> GitHub
   - Tweets -> Twitter

### Current

![image](https://user-images.githubusercontent.com/333276/230083731-858bea1d-bb99-4e29-a34a-446e29c84e4b.png)

### Proposed

![image](https://user-images.githubusercontent.com/333276/230083613-db10b76a-614a-4642-8a19-b3a0f7f76165.png)

**Comment by prudhomm** [comment]
@ggrossetie it would be nice to be able to customize the logo on the Left since the template is used for other Cemosis projects as well.
Otherwise it looks clean 

@vincentchabannes ?

**Comment by ggrossetie** [comment]
I think we should have a different header on https://docs.cemosis.fr/... it might even makes sense to use a different UI.

**Comment by prudhomm** [comment]
Cemosis may not use Feel++ for some of its project. But we do use it a lot. There is often a lot in common.
What do you suggest exactly?

**Comment by ggrossetie** [comment]
I might be wrong but I feel like https://docs.cemosis.fr/ is a showcase site for several projects (and not really a documentation site). Almost all documentation components have a single version so we could use a simpler navigation.

It's also possible to use the same UI but apply a different page template using `page-layout`: https://docs.antora.org/antora/latest/page/page-layout/
