### ISSUE TITLE
Creation of a macro for vtk.js

### ISSUE THREAD

**Issue by prudhomm** [feelpp/antora-ui#16]

**Comment by ggrossetie** [comment]
Trame is a web application with a running Python server. As far as I know the Python code is executed server-side and it has its own client/UI. I'm not sure how we can integrate it into a static web documentation site.

Whereas VTK.js and Plotly are JavaScript libraries for visualization in the browser. Am I missing something?

**Comment by prudhomm** [comment]
Trame is indeed a python webapp. basically we would need to embed it in the antora page and have a server somewhere doing the rendering. The webapp in itself is our "problem", do you think we could have a nice macro to do the embedding and configure what we see in the Trame frame ?

**Comment by prudhomm** [comment]
Trame is indeed a python webapp. basically we would need to embed it in the antora page and have a server somewhere doing the rendering. The webapp in itself is our "problem", do you think we could have a nice macro to do the embedding and configure what we see in the Trame frame ?

**Comment by prudhomm** [comment]
Trame is indeed a python webapp. basically we would need to embed it in the antora page and have a server somewhere doing the rendering. The webapp in itself is our "problem", do you think we could have a nice macro to do the embedding and configure what we see in the Trame frame ?

**Comment by prudhomm** [comment]
Trame is indeed a python webapp. basically we would need to embed it in the antora page and have a server somewhere doing the rendering. The webapp in itself is our "problem", do you think we could have a nice macro to do the embedding and configure what we see in the Trame frame ?

**Comment by ggrossetie** [comment]
> Trame is indeed a python webapp. basically we would need to embed it in the antora page and have a server somewhere doing the rendering. The webapp in itself is our "problem", do you think we could have a nice macro to do the embedding and configure what we see in the Trame frame 

As far as I understand, the UI is also defined server-side in the Python webapp.
In Antora, we can use an `<iframe>` to embed the index.html page from the trame webapp.

**Comment by vincentchabannes** [comment]
@ggrossetie je t'ai rajouté au repo [feelpp-js](https://github.com/feelpp/feelpp-js), il y a le code qui permet de générer la lib js disponible dans antora-ui. Ça fait très longtemps que je n'y a pas touché. En résumé, j'étais parti d'un example de vtk.js et  j'avais rajouté les checkbox/combobox en haut à gauche permettant de modifier la visu.

Il faudrait probablement prévoir la mise à jour de [vtk.js](https://github.com/feelpp/feelpp-js) (qui est en retard de plusieurs années) et peut-être améliorer l'interface actuelle.
