### ISSUE TITLE
Dynamic generation of a Plotly diagram from Python code

### ISSUE THREAD

**Issue by prudhomm** [feelpp/antora-ui#18]

**Comment by ggrossetie** [comment]
My proposal is to use an Asciidoctor extension to process Python source block that includes an `exec` option and a `target` attribute.



```adoc
[source%exec,python,target=result1]
----
import plotly.express as px

fig = px.line(x=["a","b","c"], y=[1,3,2], title="sample figure")
fig.show()
----

[#result1]
--
--
```

If the result should always be displayed after the source block, we can remove the target attribute.

```adoc
[source%exec,python]
----
import plotly.express as px

fig = px.line(x=["a","b","c"], y=[1,3,2], title="sample figure")
fig.show()
----

// the result will be displayed here
```

**Comment by ggrossetie** [comment]
![image](https://user-images.githubusercontent.com/333276/235703266-0f74a16d-2fa7-406c-acdd-7f812ed41103.png)

**Comment by ggrossetie** [comment]
Do you want to create a dedicated repository for Asciidoctor extensions? Alternatively, I can create this extension in https://github.com/feelpp/book.feelpp.org/tree/develop/lib

**Comment by ggrossetie** [comment]
In the example above, I'm using `pd.read_csv` with a remote URL rather than `acsv=fpp.download("github:{repo:feelpp,path:toolboxes/fluid/cases/moving_body/gravity/cylinder_under_gravity/curve_comparison.csv}", worldComm=app.worldCommPtr())[0]` in order to reduce the number of dependencies needed to generate a Plotly chart.

**Comment by prudhomm** [comment]
Regarding extension i am fine with a specific repository @ggrossetie

**Comment by prudhomm** [comment]
It all seems very good otherwise
