### ISSUE TITLE
Update admonition style

### ISSUE THREAD

**Issue by ggrossetie** [feelpp/antora-ui#2]
### Current

![image](https://user-images.githubusercontent.com/333276/230084438-972a7eff-1e4f-4a78-86ae-68720f7acd93.png)

### Proposed

![image](https://user-images.githubusercontent.com/333276/230084104-5b406f2b-c673-4579-80b6-e2653f0d3a55.png)

**Comment by prudhomm** [comment]
This seems good to me 

@vincentchabannes ?

**Comment by vincentchabannes** [comment]
also good for me!
