### ISSUE TITLE
Fix and simplify FontAwesome integration

### ISSUE THREAD

**Issue by ggrossetie** [feelpp/antora-ui#3]
- Use a npm task to generate `fontawesome-icon-defs.js` 
- Use a `fontawesome-icons.json` to declare a list of icons to include in the bundle
```json
[
  {
    "prefix": "fas",
    "iconName": "fire"
  },
  {
    "prefix": "fas",
    "iconName": "exclamation-circle"
  }
]
```
- Upgrade to FontAwesome 6.4

**Comment by prudhomm** [comment]
indeed that would be great
