### ISSUE TITLE
Improve Lemma, Proof, Proposal and Problem blocks rendering (Math)

### ISSUE THREAD

**Issue by ggrossetie** [feelpp/antora-ui#36]
![image](https://github.com/feelpp/antora-ui/assets/333276/d4a700e5-e15a-4efb-a3c9-b90a6e05407d)

![image](https://github.com/feelpp/antora-ui/assets/333276/0f1b1f2a-b57b-49ac-9b78-da9273068121)

**Comment by ggrossetie** [comment]
Fonctionne en positionnant l'un des roles suivants :

- `prob` -> Problème
- `proof` -> Preuve
- `prop` -> Proposition
- `lem` -> Lemma


Exemple :

```
[.prob#prob:2]
****
****
```

**Comment by ggrossetie** [comment]
On peut éventuellement rajouter une icône : 

- https://primer.style/design/foundations/icons/number-16
- https://primer.style/design/foundations/icons/mortar-board-16

**Comment by prudhomm** [comment]
@ggrossetie est il possible de faire en sorte que la preuve soit retractée par défaut ?

**Comment by prudhomm** [comment]
> On peut éventuellement rajouter une icône :
> 
> * https://primer.style/design/foundations/icons/number-16
> * https://primer.style/design/foundations/icons/mortar-board-16

I don't understand the purpose ?

**Comment by ggrossetie** [comment]
Yes that's the idea and the purpose is purely visual.

**Comment by ggrossetie** [comment]
> est il possible de faire en sorte que la preuve soit retractée par défaut ?

Je vais tester avec l'option collapsible d'Asciidoctor.

**Comment by ggrossetie** [comment]
![proof](https://github.com/feelpp/antora-ui/assets/333276/928af5c9-6f23-4200-aded-a815e5f35299)
